name: Sync-RIPE-ASSSET

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Sync'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
  schedule:
    - cron:  '0 0 * * *'


jobs:
  asset-sync:
    name: ASSET-SYNC
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"
    steps:
    - name: Checkout Central Actions Repo
      uses: actions/checkout@v4
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          $GITHUB_WORKSPACE/cache
        key: dst_cache 20230607
    - name: Install depends
      run: |
        sudo pip3 install pyyaml xmltodict
        sudo apt-get install -y bgpq4
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Sync ASSET to RIPE
      run: |
        python3 $GITHUB_WORKSPACE/sync_asset_a.py
      env:
        RIPE_MNT_PASSWD: ${{secrets.RIPE_MNT_PASSWD}}
        AS_SET_SRC: ${{vars.AS_SET_SRC}}
        AS_SET_DST: ${{vars.AS_SET_DST_RIPE}}
        MAX_DEPTH: ${{vars.MAX_DEPTH}}
        MEM_CACHE_FILE: ${{vars.MEM_CACHE_FILE}}
      shell: bash
    - name: Sync ASSET to ARIN
      run: |
        python3 $GITHUB_WORKSPACE/sync_asset_b.py
      env:
        ARIN_APIKEY: ${{secrets.ARIN_APIKEY}}
        AS_SET_DST: ${{vars.AS_SET_DST_ARIN}}
        MEM_CACHE_FILE: ${{vars.MEM_CACHE_FILE}}
      shell: bash
    - name: wrtie something to prevent this action inactive
      run: |
        echo $(date +%Y-%m-%d/%H:%M:%S) > $GITHUB_WORKSPACE/sync
      shell: bash
    - name: Commit
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "keep-gha"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: keep-gha
        force: true
